module Language.DmsGrammar.TermInstances where

import Language.DmsGrammar.Syntax
import TermRep

{- Generated by DrIFT (Automatic class derivations for Haskell) -}
{-# LINE 1 "Syntax.hs" #-}
{-* Generated by DrIFT : Look, but Don't Touch. *-}
instance Term DmsSyntax where
    explode (x::DmsSyntax) = TermRep (toDyn x, f x, g x) where
	f (DmsSyntax aa) = [explode aa]
	g (DmsSyntax _) xs = case TermRep.fArgs xs of [aa] -> toDyn ((DmsSyntax (TermRep.fDyn aa))::DmsSyntax) ; _ -> error "Term explosion error."

_tc_DmsSyntaxTc = mkTyCon "DmsSyntax"
instance Typeable DmsSyntax where
    typeOf x = mkTyConApp _tc_DmsSyntaxTc [ ]

instance Term DmsRule where
    explode (x::DmsRule) = TermRep (toDyn x, f x, g x) where
	f (Other aa ab) = [explode aa,explode ab]
	f (Rule ac ad ae) = [explode ac,explode ad,explode ae]
	f (Disambiguation af) = [explode af]
	g (Other _ _) xs = case TermRep.fArgs xs of [aa,ab] -> toDyn ((Other (TermRep.fDyn aa) (TermRep.fDyn ab))::DmsRule) ; _ -> error "Term explosion error."
	g (Rule _ _ _) xs = case TermRep.fArgs xs of [ac,ad,ae] -> toDyn ((Rule (TermRep.fDyn ac) (TermRep.fDyn ad) (TermRep.fDyn ae))::DmsRule) ; _ -> error "Term explosion error."
	g (Disambiguation _) xs = case TermRep.fArgs xs of [af] -> toDyn ((Disambiguation (TermRep.fDyn af))::DmsRule) ; _ -> error "Term explosion error."

_tc_DmsRuleTc = mkTyCon "DmsRule"
instance Typeable DmsRule where
    typeOf x = mkTyConApp _tc_DmsRuleTc [ ]

instance Term DmsSymbol where
    explode (x::DmsSymbol) = TermRep (toDyn x, f x, g x) where
	f (DmsNonTerminal aa) = [explode aa]
	f (DmsTerminal ab) = [explode ab]
	g (DmsNonTerminal _) xs = case TermRep.fArgs xs of [aa] -> toDyn ((DmsNonTerminal (TermRep.fDyn aa))::DmsSymbol) ; _ -> error "Term explosion error."
	g (DmsTerminal _) xs = case TermRep.fArgs xs of [ab] -> toDyn ((DmsTerminal (TermRep.fDyn ab))::DmsSymbol) ; _ -> error "Term explosion error."

_tc_DmsSymbolTc = mkTyCon "DmsSymbol"
instance Typeable DmsSymbol where
    typeOf x = mkTyConApp _tc_DmsSymbolTc [ ]

--  Imported from other files :-
